server:
  port: 9041
  address: '[::]'
spring:
  application:
    name: authentication-service
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: mail-producer
env:
  backend:
    urls:
      UserService: http://localhost:9011/userService
      RoleService: http://localhost:9012/roleService
      UserRoleService: http://localhost:9013/userRoleService
      PersonService: http://localhost:9021/personService
      JWTService: http://localhost:9031/jwtService
    email:
      newUserTisserIdTemplate: 10
    kafka:
      topic: email-topic